[package]
name = "dmg_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_dmg = {path = "lib_dmg"}
minifb = "0.25.0"
